blank_issues_enabled: true
contact_links:
  - name: General Support Request
    url: https://github.com/AxeWP/wp-graphql-facetwp/discussions
    about: For general help requests, create a new topic in Github Discussions
  - name: Premium Support Request
    url: https://axepress.dev/contact/
    about: For premium support requests, custom development, or to sponsor a feature, please contact us directly.
  - name: Discord Community
    url: https://discord.gg/GyKncfmn7q
    about: The WPGraphQL Discord is a great place to communicate in real-time. Ask questions, discuss features, get to know other folks using WPGraphQL.
